menu:
- {name: 'About Me', url: '/about'}
- {name: 'Projects', url: '/projects'}
- {name: 'Experiences', url: '/experiences'}
- {name: 'Awards', url: '/awards'}
- {name: 'Education', url: '/education'}
# - {name: 'contact', url: '/contact'}

projects:
- {name4: 'Skateboard Brake',
  bullet_41: 'I love skating around campus, though sometimes going fast can lead to safety issues. To address this, my team and I decided to invent a skateboard brake that maximizes skater safety. During customer discovery,
  we realized skaters were interested in this product due to its convenience and lower cost compared to electric skateboards. Our goal was to modularize our product to provide the convenience that customers want while addressing the safety concern.',
  bullet_42: 'Considering the longevity and braking force required, our team explored permanent magnets and Eddy current braking as a potential solution. After conducting experiments, our minimum viable product confirmed our hypothesis that this approach is viable for our product.',
  image4: 'assets/img/skate.jpg',
  name: 'Dual Barrel Mechanism',
  bullet_11: 'Project Planning: Researched practicable mechanic ideas, hand-sketching the systems, and distributing reports to the mechanical team.',
  bullet_12: 'Product Designed: CADed and combined the individual components, including a worm gear system, a linear slide support system, and 3d printed mounts.',
  bullet_13: 'Analytic Result: 3D printed and fabricated the system for the Infantry robot which increase the overall shooting efficiency by 50%.',
  image: 'assets/img/dual-barrel.JPG',
  name2: 'Scissor Lift Mechanism',
  bullet_21: 'Designed and implemented a scissor lift mechanism involving lifting and precise positioning, resulting in increased efficiency.',
  bullet_22: 'Analyzed the components, dimensions, and materials of the lift to calculate theoretical and experimental values, as well as the factor of safety.',
  bullet_23: 'Utilized SolidWorks and AutoCAD to create detailed designs and technical drawings of the scissor lift mechanism, including all moving parts and mechanical linkages.',
  image2: 'assets/img/scissorlift.png',
  name3: 'Gamepad Controller',
  bullet_31: 'User Experience: 3D modeled and manufactured a gamepad controller, including designed the controller handles and button placement, for optimal user experience based on the exterior design of the PS4.',
  bullet_32: 'Electronics: Designed and welded plastic circuit boards with main hardware components to ensure effective
connections and reliable usage.',
  bullet_33: 'Innovative Ideas: Incorporated innovative ideas, such as a captive nuts design, to enhance the stability and accessibility of the project.',
  bullet_34: 'Group Project: Collaborated with team members and implemented a game interface using Linux programming to create a series of old arcade games on Raspberry pi game console.',
  image3: 'assets/img/ps4_up.jpg'
  }

experiences:
- {name: 'Logitech Gaming',
  position: 'Mechanical Engineering Intern',
  bullet_11: 'During my sophomore summer, I had the opportunity to work as a mechanical engineering intern with the Logitech Gaming team. I spent two months collaborating with professionals, including engineers from various departments.',
  bullet_12: 'My main responsibility was designing a mechanism for a new gaming mouse. While the details I can share are limited, I contributed to mechanical research, innovative designs, and functional prototypes. I also gained experience in CAD modeling, force analysis simulation, experimental testing, and performance optimization.',
  bullet_13: 'Conducted comprehensive testing, comparing and analyzing experimental results with functional prototypes to validate performance and optimize the design.',
  bullet_14: 'Collaborated within a team of 30+ engineers and frequently cooperated with other gaming departments.',
  image: 'assets/img/logi.JPG',
  name2: 'Triton Robotics',
  position2: 'Mechanical Engineer',
  bullet_21: 'During my two years with Triton Robotics, I worked on the Infantry team, focusing on designing mechanisms and resolving hardware issues. I participated in several projects, including the design of a dual barrel mechanism to enhance shooting performance.',
  bullet_22: 'We competed twice in the annual Robomaster competition. This valuable experience allowed me to learn a lot from my colleagues, including 3D modeling, mechanical design, manufacturing, and machine assembly.',
  image2: 'assets/img/tr.jpeg',
  name3: 'VEX Robotics',
  position3: 'Mechanical Engineer',
  bullet_31: 'I participated in the VEX robotics club team during high school. Throughout the year, our team competed in many events and were the 2nd runner-up in the national competition.',
  bullet_32: 'Our role was to design and build robots, encompassing both hardware and software, to complete specific tasks in various competitions. Throughout this experience,
  I developed skills in manufacturing, experimental testing, and robotics.',
  bullet_33: 'Innovative Ideas: Incorporated innovative ideas, such as a captive nuts design, to enhance the stability and accessibility of the project.',
  image3: 'assets/img/vex.jpg'
  }


awards:
- {name: 'IEEE Hardware Hackathon',
  bullet_1: 'Built an autonomous car that utilized wireless communication signals for navigation and won first place in the WCSNG challenge at the hardware hackathon.',
  image: 'assets/img/HardHack1.JPG'}
  # name2: 'Scissor Lift',
  # 2-1: 'CAD Design: Designed and developed a scissor lift robot for class robotics competition using SolidWorks and AutoCAD.',
  # 2-2: 'Troubleshoot: Conducted testing and troubleshooting to identify and resolve issues in the lift's operation.',
  # 2-3: 'Final Report: Delivered a report for all design changes, testing results, and maintenance activities.'}
# - {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
# - {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/Allenwu1122'}
# - {icon: 'twitter', link: 'https://twitter.com/paululele'}
# - {icon: 'instagram', link: 'https://www.instagram.com/allen.wu3/?hl=en'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/allen-wu-307451229/'}
# - {icon: 'envelope',  link: 'mailto:yalunwu1122@gmail.com'}

contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
